# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: silverblue-kiosk
description: Read-only automated Moonlight Kiosk terminal.
base-image: quay.io/fedora-ostree-desktops/silverblue
image-version: 40

modules:
  - type: rpm-ostree
    install:
      - cage
      - flatpak
      - curl
      - mesa-dri-drivers
      - xrandr
      - newt