# .github/workflows/iso.yml
name: Generate Bootable ISO
on:
  workflow_run:
    workflows: ["Build Custom Silverblue Kiosk Image"]
    types:
      - completed

jobs:
  build-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Generate ISO via BlueBuild
        uses: blue-build/apps-action@v1
        with:
          recipe: 'config/recipe.yml'