name: Build Custom Silverblue Kiosk Image
on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: "silverblue-kiosk"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Image using BlueBuild
        uses: blue-build/github-action@v1.8.1
        with:
          recipe: 'recipe.yml'
          build_opts: '--no-sign'
          working_directory: './'